Mobile memory disposal pattern+UI elements
geocortex/dev-center pull request #89
Opened 2021-06-18 05:31 UTC by Felicity-R

Document some stuff for mobile:
https://geocortex.visualstudio.com/Geocortex/_workitems/edit/40023
https://geocortex.visualstudio.com/Geocortex/_workitems/edit/41574/

2021-06-18 17:25 UTC, rcooney approved these changes

2021-06-21 16:56 UTC, jsiemensLatitudegeo requested changes

2021-06-21 17:36 UTC, Felicity-R commented on docs/mobile/sdk-memory-leaks.mdx
> +        SafeFileHandle handle = new SafeFileHandle(IntPtr.Zero, true);
Fixed

2021-06-21 17:37 UTC, Felicity-R commented on docs/mobile/sdk-components-styling.mdx
>  Geocortex Mobile XAML Elements, like the `EnhancedButton` or `EnhancedSwitch` can ease the development of custom components with the SDK. Check out the [relevant SDK sample](https://github.com/geocor
Changed 'XAML Elements' to 'Views' throughout this page

2021-06-21 17:37 UTC, Felicity-R commented on docs/mobile/sdk-memory-leaks.mdx
> +## Using Mobile's IDisposableTracker Interface
Added brief note with links to the Commands and Operations and Events sections

2021-06-21 17:38 UTC, Felicity-R commented on docs/mobile/sdk-memory-leaks.mdx
> +Classes instantiated in Mobile via [dependency injection](sdk-dependency-injection.mdx) will automatically be disposed by Autofac, and do not need to be disposed of manually by the developer.
Reworded in a way which should make it clearer that it's just the call to Dispose() that's taken care of by AutoFac, not the actual implementation of IDisposable.

2021-06-21 17:39 UTC, Felicity-R commented on docs/mobile/sdk-memory-leaks.mdx
> +`ComponentBase` and `ServiceBase` already implement `IDisposableTracker`, so any custom components or services extending these base classes can take advantage of this functionality right away. Here i
Added a note to this effect

2021-06-21 18:59 UTC, jsiemensLatitudegeo approved these changes

2021-06-21 19:07 UTC, merged